version: '3.9'

services:
  database: 
    image: postgres
    container_name: Lista
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local